on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name:  Login to container registry
        uses: docker/login-action@2
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrete.GITHUB_TOKEN }}
      
      - name: Build Project
        uses: docker/build-push-action@v4
        with: 
          tag: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.run_number }}
